[project]
name = "makler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "k0vcheg", email = "52414665+ichepyxa@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pyside6>=6.11.2",
    "sqlalchemy>=2.1.2",
]

[project.scripts]
makler = "makler:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyinstaller>=6.22.3",
    "pytest>=9.1.1",
    "ruff>=0.16.10",
]
